# Generated by Django 3.2.4 on 2021-07-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210713_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
